name:                ti-project
version:             0.1.0.0
github:              "githubuser/ti-project"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ti-project#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- hspec

library:
  source-dirs: src

executables:
  ti-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ti-project

tests:
  ti-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ti-project

ghc-options:
- -Werror                   # warnings are errors
- -Wincomplete-patterns     # cover all cases!
- -Wunused-binds            # use all your bindings
- -Wunused-matches          # use all your pattern matches!
- -Wmissing-signatures      # write all your toplevel signatures!
- -Wname-shadowing          # use different names!
- -Wincomplete-uni-patterns # warn about incomplete patterns v2
- -Wall
